"""wave_banks.py — which .bin wave bank owns a given raw stream.

Data (launcher/data/, see resources.data_path):
  audio_wave_banks.json   {vol, pairs, banks: {"1A/1B": {name: {base, end, size}}, ...}}
                          generated by emit_wave_banks.py from the 0A archive TOC.

The raw XMA2 containers are not 19 separate files -- they are a handful of container files that
together hold 19 logical `.bin` wave banks laid end to end. A pair like 1A + 1B is ONE logical byte
space: an offset below `vol` (0x6B800000) sits in the first file at that offset, and anything at or
above it sits in the second file at `logical - vol`.

Every bank is an ordinary entry in the 0A archive TOC named "<bank>.bin", so each span's base AND
size are exact archive facts, not inferred from where the next bank starts. That matters at the
edges: a bank owns [base, end), and outside every span the answer is "no bank" -- the bytes past
teams.bin in 1B are .iff assets that merely happen to contain audio, and reporting them as
teams.bin (which a base-only layout does, since its last span has no upper bound) is simply wrong.

This is a different axis from audio_names.bank_info(). That answers "which arena_*.iff sound banks
REFERENCE this stream" (a team/usage question, many-to-one). This answers "which .bin does this
stream physically LIVE in" (a storage question, exactly one). Both are useful and neither replaces
the other: the Audio tab's "Bank / Team" column tells you Vancouver uses a stream, while the "Bin"
column tells you it is stored in horns.bin.
"""
from __future__ import annotations
import json

try:
    from . import resources
except ImportError:                                     # flat import when run un-packaged
    import resources

_layout: dict | None = None


def _load() -> dict:
    """{first_fid: (vol, [(name, base, end), ...])} keyed by BOTH files of each pair"""
    global _layout
    if _layout is not None:
        return _layout
    _layout = {}
    try:
        doc = json.loads(resources.data_path("audio_wave_banks.json")
                         .read_text(encoding="utf-8"))
    except Exception:
        return _layout
    vol = int(doc.get("vol") or 0)
    pairs = {}
    for p in doc.get("pairs") or []:
        key = "%s/%s" % (p.get("first"), p.get("second"))
        pairs[key] = (p.get("first"), p.get("second"))
    for key, banks in (doc.get("banks") or {}).items():
        if key not in pairs:
            continue
        # `end` comes from the TOC size; fall back to the next base only for an older data file
        ordered = sorted(((n, int(e["base"]), e.get("end")) for n, e in banks.items()),
                         key=lambda kv: kv[1])
        spans = [(n, b, int(e) if e is not None else
                  (ordered[i + 1][1] if i + 1 < len(ordered) else (1 << 62)))
                 for i, (n, b, e) in enumerate(ordered)]
        first, second = pairs[key]
        for fid in (first, second):
            if fid:
                _layout[fid] = (vol, spans, first)
    return _layout


def bank_for(fid: str, offset) -> str:
    """Display name of the .bin owning this stream, or "" when unknown.

    `offset` is the physical offset within `fid`; it is converted to the pair's logical space
    before lookup, which is why the second file of a pair needs `vol` added back.
    """
    if offset is None:
        return ""
    lay = _load().get((fid or "").upper())
    if not lay:
        return ""
    vol, spans, first = lay
    logical = int(offset) if (fid or "").upper() == first else int(offset) + vol
    for name, lo, hi in spans:
        if lo <= logical < hi:
            return name
    return ""


# ── sample rate ───────────────────────────────────────────────────────────────
#
# The rate is a property of the BANK, not of the stream: raw XMA2 packets carry no sample rate
# at all (the rate lives in the RIFF `fmt ` chunk the decoder is handed), so decoding at the
# wrong rate does not fail -- it silently resamples. Everything used to be decoded at 48000,
# which made the 44.1 kHz banks play 48000/44100 = 8.8% fast, i.e. about a semitone and a half
# sharp. That is what "pamusic.bin extracted at too high of a pitch" was.
#
# Source: the speech cue table header in gamedata.iff / global.iff --
#   [count u32][hash u32][1][sample_rate u32][0x800][channels u32]
# one table per bank, 19 of the 23 banks. See findings/04 §14.
#
# Independently CONFIRMED for 17 of those 19 by a completely separate measurement: the cue
# records carry a per-cue duration, and the XMA2 bitstream fixes the sample COUNT, so
#   cue_duration / duration_decoded_at_48k == 48000 / true_rate
# Over 17 banks and 76,000 cues that ratio is 1.0000 or 1.0884 to four decimals, exactly as the
# header says. horns.bin's cues declare a window longer than the horn (see project goal-horn
# notes) so its ratio is only 1.000 on the rows that are not padded -- those confirm 48000.
# jukeboxmusic.bin and femusic.bin are multi-stream/5.1 and their records do not parse yet, so
# they rest on the header field alone.
BANK_RATES = {
    # 44.1 kHz -- crowd, PA and arena content
    "chants.bin":              44100,
    "chatter.bin":             44100,
    "streamedchatter.bin":     44100,
    "palines.bin":             44100,
    "paplyrs.bin":             44100,
    "pamusic.bin":             44100,
    # 48 kHz -- the booth, and the ambience beds
    "crowd.bin":               48000,
    "crowd-idle-loop.bin":     48000,
    "env_amb.bin":             48000,
    "horns.bin":               48000,
    "lines.bin":               48000,
    "lines_ps.bin":            48000,
    "lines_ts.bin":            48000,
    "players.bin":             48000,
    "playercom.bin":           48000,
    "playercom2.bin":          48000,
    "teams.bin":               48000,
    "jukeboxmusic.bin":        48000,     # header only -- records do not parse (5.1)
    "femusic.bin":             48000,     # header only -- 2 KB stub, one cue
}

# The four front-end banks have no name and therefore no cue table (see emit_wave_banks.py and
# the FF3BEF94 note in findings/04), so their rate is the only part of the audio catalogue that
# is NOT read out of the data. 192 streams, 0.24% of the catalogue. 48000 is the assumption:
# they sit immediately after jukeboxmusic.bin, they are front-end announcer/menu-music content,
# and the two banks either side of them are 48000. If one of them ever sounds sharp or flat,
# change it here -- do not reintroduce a per-stream rate the user has to guess at.
DEFAULT_RATE = 48000


def rate_for(fid: str, offset) -> int:
    """Sample rate this stream must be decoded at. Never guesses per stream -- see BANK_RATES."""
    return BANK_RATES.get(bank_for(fid, offset), DEFAULT_RATE)


def all_banks() -> list:
    """Every bank display name, in layout order, for populating a filter dropdown."""
    seen, out = set(), []
    for fid in sorted(_load()):
        vol, spans, first = _load()[fid]
        if fid != first:
            continue
        for name, _lo, _hi in spans:
            disp = name
            if disp not in seen:
                seen.add(disp)
                out.append(disp)
    return out
