"""wave_banks.py — which .bin wave bank owns a given raw stream.

Data (launcher/data/, see resources.data_path):
  audio_wave_banks.json   {vol, pairs, banks: {"1A/1B": {name: {base, end, size}}, ...}}
                          generated by emit_wave_banks.py from the 0A archive TOC.

The raw XMA2 containers are not 19 separate files -- they are a handful of container files that
together hold 19 logical `.bin` wave banks laid end to end. A pair like 1A + 1B is ONE logical byte
space: an offset below `vol` (0x6B800000) sits in the first file at that offset, and anything at or
above it sits in the second file at `logical - vol`.

Every bank is an ordinary entry in the 0A archive TOC named "<bank>.bin", so each span's base AND
size are exact archive facts, not inferred from where the next bank starts. That matters at the
edges: a bank owns [base, end), and outside every span the answer is "no bank" -- the bytes past
teams.bin in 1B are .iff assets that merely happen to contain audio, and reporting them as
teams.bin (which a base-only layout does, since its last span has no upper bound) is simply wrong.

This is a different axis from audio_names.bank_info(). That answers "which arena_*.iff sound banks
REFERENCE this stream" (a team/usage question, many-to-one). This answers "which .bin does this
stream physically LIVE in" (a storage question, exactly one). Both are useful and neither replaces
the other: the Audio tab's "Bank / Team" column tells you Vancouver uses a stream, while the "Bin"
column tells you it is stored in horns.bin.
"""
from __future__ import annotations
import json

try:
    from . import resources
except ImportError:                                     # flat import when run un-packaged
    import resources

_layout: dict | None = None

# Banks that have MOVED out of the shipped layout: {bank: (fid, offset, end)} in that file's own
# PHYSICAL offsets. See `set_live_layout`.
_moved: dict = {}


def _load() -> dict:
    """{first_fid: (vol, [(name, base, end), ...])} keyed by BOTH files of each pair"""
    global _layout
    if _layout is not None:
        return _layout
    _layout = {}
    try:
        doc = json.loads(resources.data_path("audio_wave_banks.json")
                         .read_text(encoding="utf-8"))
    except Exception:
        return _layout
    vol = int(doc.get("vol") or 0)
    pairs = {}
    for p in doc.get("pairs") or []:
        key = "%s/%s" % (p.get("first"), p.get("second"))
        pairs[key] = (p.get("first"), p.get("second"))
    for key, banks in (doc.get("banks") or {}).items():
        if key not in pairs:
            continue
        # `end` comes from the TOC size; fall back to the next base only for an older data file
        ordered = sorted(((n, int(e["base"]), e.get("end")) for n, e in banks.items()),
                         key=lambda kv: kv[1])
        spans = [(n, b, int(e) if e is not None else
                  (ordered[i + 1][1] if i + 1 < len(ordered) else (1 << 62)))
                 for i, (n, b, e) in enumerate(ordered)]
        first, second = pairs[key]
        for fid in (first, second):
            if fid:
                _layout[fid] = (vol, spans, first)
    return _layout


def set_live_layout(game_dir, log=None) -> dict:
    """Note any wave bank the LIVE archive TOC no longer has where the shipped layout says.

    The layout this module ships describes the disc: two pairs, each one logical byte space, every
    bank at a fixed base inside it. That is exact until a bank is GROWN -- growing one past its
    neighbour is impossible in place, so it gets relocated to the end of the archive set, which on
    this install means a fifth container (1C). A relocated bank is then in no shipped span at all,
    so `bank_for` returns "" for every one of its streams and they extract as Unknown/ with no
    bank, no line table and the default sample rate.

    The TOC is the authority on where a bank actually is, so ask it, and record only the banks whose
    answer differs from the shipped layout. Physical offsets, no logical fold: `resolve` already
    reports (archive, offset within that archive), which is the same coordinate the audio manifest
    stores, so there is nothing to convert and no `vol` to get wrong.

    Idempotent, and safe to call with no game dir or a stock install -- both leave `_moved` empty
    and every lookup falls through to the shipped layout exactly as before.
    """
    global _moved
    _moved = {}
    try:
        try:
            from . import archive_textures as AT
        except ImportError:
            import archive_textures as AT
        from pathlib import Path
        game_dir = Path(game_dir)
        if not (game_dir / "0A").is_file():
            return _moved
        lay = _load()
        seen = set()
        for fid, (vol, spans, first) in list(lay.items()):
            if fid != first:
                continue                          # spans are per PAIR, not per file
            for name, lo, _hi in spans:
                if name in seen:
                    continue
                seen.add(name)
                try:
                    arc, off, size = AT.resolve(name, game_dir)[:3]
                except Exception:
                    continue
                arc, off = arc.upper(), int(off)
                # fold the answer back into this pair's logical space to compare like with like:
                # the shipped base is logical, `resolve` is physical within one file.
                if arc in lay and lay[arc][2] == first:
                    if (off if arc == first else off + vol) == lo:
                        continue                  # still where the shipped layout says
                _moved[name] = (arc, off, off + int(size))
    except Exception as e:
        if log:
            log(f"[audio] live wave-bank layout not read ({e}); using the shipped layout")
        _moved = {}
    if _moved and log:
        for n, (a, o, e) in sorted(_moved.items()):
            log(f"[audio] {n} has been relocated to {a} @0x{o:08X} ({e - o:,} B)")
    return _moved


def moved() -> dict:
    """{bank: (fid, offset, end)} for banks the live TOC has moved. Empty on a stock install."""
    return _moved


def bank_for(fid: str, offset) -> str:
    """Display name of the .bin owning this stream, or "" when unknown.

    `offset` is the physical offset within `fid`; it is converted to the pair's logical space
    before lookup, which is why the second file of a pair needs `vol` added back.

    Relocated banks are checked FIRST and in physical coordinates, because a bank that has moved
    no longer has a meaningful base in the shipped logical space -- and because the bytes it left
    behind are still sitting in the old span, so the shipped answer there is not merely stale, it
    names a bank that has since been replaced.
    """
    if offset is None:
        return ""
    up, off = (fid or "").upper(), int(offset)
    for name, (mfid, lo, hi) in _moved.items():
        if up == mfid and lo <= off < hi:
            return name
    lay = _load().get(up)
    if not lay:
        return ""
    vol, spans, first = lay
    logical = off if up == first else off + vol
    for name, lo, hi in spans:
        if lo <= logical < hi:
            return name if name not in _moved else ""
    return ""


def span_of(fid: str, offset):
    """(lo, hi) of the bank owning this stream, in `fid`'s own PHYSICAL offsets, or None.

    `bank_for` answers "which bank", which is enough to label a stream. A WRITE needs the other
    half of the fact: a slot may start inside a bank and, at its declared packet count, run out
    the far end of it. The bytes past the end belong to whatever the TOC puts there next, so a
    caller that is about to `seek(off); write(n)` has to be able to check `off + n <= hi`.

    Returns physical coordinates so the answer can be compared directly against the offset the
    audio manifest stores; the logical fold used by the shipped layout is undone before returning.
    """
    if offset is None:
        return None
    up, off = (fid or "").upper(), int(offset)
    for _name, (mfid, lo, hi) in _moved.items():
        if up == mfid and lo <= off < hi:
            return lo, hi
    lay = _load().get(up)
    if not lay:
        return None
    vol, spans, first = lay
    logical = off if up == first else off + vol
    shift = 0 if up == first else vol
    for name, lo, hi in spans:
        if lo <= logical < hi:
            return (None if name in _moved else (lo - shift, hi - shift))
    return None


# ── sample rate ───────────────────────────────────────────────────────────────
#
# The rate is a property of the BANK, not of the stream: raw XMA2 packets carry no sample rate
# at all (the rate lives in the RIFF `fmt ` chunk the decoder is handed), so decoding at the
# wrong rate does not fail -- it silently resamples. Everything used to be decoded at 48000,
# which made the 44.1 kHz banks play 48000/44100 = 8.8% fast, i.e. about a semitone and a half
# sharp. That is what "pamusic.bin extracted at too high of a pitch" was.
#
# Source: the speech cue table header in gamedata.iff / global.iff --
#   [count u32][hash u32][1][sample_rate u32][0x800][channels u32]
# one table per bank, 19 of the 23 banks. See findings/04 §14.
#
# Independently CONFIRMED for 17 of those 19 by a completely separate measurement: the cue
# records carry a per-cue duration, and the XMA2 bitstream fixes the sample COUNT, so
#   cue_duration / duration_decoded_at_48k == 48000 / true_rate
# Over 17 banks and 76,000 cues that ratio is 1.0000 or 1.0884 to four decimals, exactly as the
# header says. horns.bin's cues declare a window longer than the horn (see project goal-horn
# notes) so its ratio is only 1.000 on the rows that are not padded -- those confirm 48000.
# jukeboxmusic.bin and femusic.bin are multi-stream/5.1 and their records do not parse yet, so
# they rest on the header field alone.
BANK_RATES = {
    # 44.1 kHz -- crowd, PA and arena content
    "chants.bin":              44100,
    "chatter.bin":             44100,
    "streamedchatter.bin":     44100,
    "palines.bin":             44100,
    "paplyrs.bin":             44100,
    "pamusic.bin":             44100,
    # 48 kHz -- the booth, and the ambience beds
    "crowd.bin":               48000,
    "crowd-idle-loop.bin":     48000,
    "env_amb.bin":             48000,
    "horns.bin":               48000,
    "lines.bin":               48000,
    "lines_ps.bin":            48000,
    "lines_ts.bin":            48000,
    "players.bin":             48000,
    "playercom.bin":           48000,
    "playercom2.bin":          48000,
    "teams.bin":               48000,
    "jukeboxmusic.bin":        48000,     # header only -- records do not parse (5.1)
    "femusic.bin":             48000,     # header only -- 2 KB stub, one cue
}

# The four front-end banks have no name and therefore no cue table (see emit_wave_banks.py and
# the FF3BEF94 note in findings/04), so their rate is the only part of the audio catalogue that
# is NOT read out of the data. 192 streams, 0.24% of the catalogue. 48000 is the assumption:
# they sit immediately after jukeboxmusic.bin, they are front-end announcer/menu-music content,
# and the two banks either side of them are 48000. If one of them ever sounds sharp or flat,
# change it here -- do not reintroduce a per-stream rate the user has to guess at.
DEFAULT_RATE = 48000


def rate_for(fid: str, offset) -> int:
    """Sample rate this stream must be decoded at. Never guesses per stream -- see BANK_RATES."""
    return BANK_RATES.get(bank_for(fid, offset), DEFAULT_RATE)


def all_banks() -> list:
    """Every bank display name, in layout order, for populating a filter dropdown."""
    seen, out = set(), []
    for fid in sorted(_load()):
        vol, spans, first = _load()[fid]
        if fid != first:
            continue
        for name, _lo, _hi in spans:
            disp = name
            if disp not in seen:
                seen.add(disp)
                out.append(disp)
    return out
